name: User's Guide
on:
    push:  # Build the docs for any branch (we only push to GCP when building from main)
    pull_request:  # Build the docs for any PR
    create:  # Any time a tag (or branch) is added, rebuild the docs.

jobs:
    build-ug:
        name: Sphinx docs
        runs-on: ubuntu-latest
        defaults:
          run:
            shell: bash -l {0}

        steps:
            - uses: actions/checkout@v1

            - name: Set up python
              uses: actions/setup-python@v1
              with:
                  python-version: "3.10"

            - name: Setup conda environment
              uses: conda-incubator/setup-miniconda@v2
              with:
                  activate-environment: env
                  auto-update-conda: true
                  python-version: "3.10"
                  channels: conda-forge

            - name: Install python dependencies with conda
              run: conda env update --file environment.yml

            - name: Run custom extension tests
              run: make test_investspec

            - name: Build sphinx docs
              run: make html

            - name: Check links
              # this has rarely run for hours for no apparent reason
              timeout-minutes: 2
              continue-on-error: true
              run: make linkcheck

            - name: Set up GCP SDK
              if: ${{ github.ref == 'refs/heads/main' }}
              uses: google-github-actions/setup-gcloud@v0
              with:
                  version: '281.0.0'
                  service_account_key: ${{ secrets.GCP_SERVICE_ACC_KEY }}

            - name: Upload to GCS
              if: ${{ github.ref == 'refs/heads/main' }}
              run: |
                BUCKET=gs://releases.naturalcapitalproject.org/invest-userguide/latest
                gsutil -m rsync -dr build/html $BUCKET
                # Cache appears to be reset each time we upload a new blob.
                # Re-set the cache here to allow UG editors to immediately view
                # changes to the rendered HTML.
                gsutil -m setmeta -r -h "Cache-control:no-store" $BUCKET

            - name: Save UG artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: InVEST User's Guide
                  path: build/html
